version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - .:/myapp
      - bundle_cache:/usr/local/bundle
    working_dir: /myapp

volumes:
  bundle_cache:
